export const skillIcons = {
  "ChromaDB": "https://api.iconify.design/logos:chroma.svg",
  "Chroma": "https://api.iconify.design/logos:chroma.svg",
  "LlamaIndex": "https://raw.githubusercontent.com/run-llama/llama_index/main/docs/api_reference/api_reference/_static/assets/LlamaLogoBrowserTab.png",
  "LangChain": "https://cdn.simpleicons.org/langchain/white",
  "OpenCV": "https://raw.githubusercontent.com/devicons/devicon/master/icons/opencv/opencv-original.svg",
  "YOLO": "https://cdn.simpleicons.org/ultralytics/white",
  "YOLO v11": "https://cdn.simpleicons.org/ultralytics/white",
  "MediaPipe": "https://cdn.simpleicons.org/mediapipe/white",
  "ONNX": "https://cdn.simpleicons.org/onnx/white",
  "PyTorch": "https://raw.githubusercontent.com/devicons/devicon/master/icons/pytorch/pytorch-original.svg",
  "TensorFlow": "https://raw.githubusercontent.com/devicons/devicon/master/icons/tensorflow/tensorflow-original.svg",
  "Keras": "https://cdn.simpleicons.org/keras/white",
  "Pandas": "https://raw.githubusercontent.com/devicons/devicon/master/icons/pandas/pandas-original.svg",
  "NumPy": "https://raw.githubusercontent.com/devicons/devicon/master/icons/numpy/numpy-original.svg",
  "Scikit-learn": "https://cdn.simpleicons.org/scikitlearn/white",
  "Scikit-Learn": "https://cdn.simpleicons.org/scikitlearn/white",
  "Hugging Face": "https://cdn.simpleicons.org/huggingface/white",
  "Python": "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg",
  "C++": "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg",
  "Docker": "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original.svg",
  "Linux": "https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg",
  "Next.js": "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg",
  "MongoDB": "https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original.svg",
  "PostgreSQL": "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg",
  "Git": "https://raw.githubusercontent.com/devicons/devicon/master/icons/git/git-original.svg",
  "uv": "https://cdn.simpleicons.org/uv/white",
  "FastAPI": "https://raw.githubusercontent.com/devicons/devicon/master/icons/fastapi/fastapi-original.svg",
  "Flask": "https://raw.githubusercontent.com/devicons/devicon/master/icons/flask/flask-original.svg",
  "React": "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg"
};
