export const skillIcons = {
  "PyTorch": "https://raw.githubusercontent.com/devicons/devicon/master/icons/pytorch/pytorch-original.svg",
  "TensorFlow": "https://raw.githubusercontent.com/devicons/devicon/master/icons/tensorflow/tensorflow-original.svg",
  "OpenCV": "https://raw.githubusercontent.com/devicons/devicon/master/icons/opencv/opencv-original.svg",
  "YOLO v11": "https://cdn.simpleicons.org/ultralytics/white",
  "YOLO": "https://cdn.simpleicons.org/ultralytics/white",
  "Python": "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg",
  "MediaPipe": "https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/google.svg",
  "C++": "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg",
  "C": "https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg",
  "Arduino": "https://raw.githubusercontent.com/devicons/devicon/master/icons/arduino/arduino-original.svg",
  "Git": "https://raw.githubusercontent.com/devicons/devicon/master/icons/git/git-original.svg",
  "Docker": "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original.svg",
  "Kubernetes": "https://raw.githubusercontent.com/devicons/devicon/master/icons/kubernetes/kubernetes-plain.svg",
  "LangChain": "https://cdn.simpleicons.org/langchain/white",
  "React": "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg",
  "Tailwind CSS": "https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-original.svg",
  "Vite": "https://raw.githubusercontent.com/devicons/devicon/master/icons/vitejs/vitejs-original.svg",
  "Firebase": "https://raw.githubusercontent.com/devicons/devicon/master/icons/firebase/firebase-plain.svg",
  "FastAPI": "https://raw.githubusercontent.com/devicons/devicon/master/icons/fastapi/fastapi-original.svg",
  "Flask": "https://raw.githubusercontent.com/devicons/devicon/master/icons/flask/flask-original.svg",
  "NumPy": "https://raw.githubusercontent.com/devicons/devicon/master/icons/numpy/numpy-original.svg",
  "Pandas": "https://raw.githubusercontent.com/devicons/devicon/master/icons/pandas/pandas-original.svg",
  "Keras": "https://cdn.simpleicons.org/keras/white",
  "Pinecone": "https://cdn.simpleicons.org/pinecone/white",
  "UNet++": "https://raw.githubusercontent.com/devicons/devicon/master/icons/pytorch/pytorch-original.svg",
  "VGG16": "https://raw.githubusercontent.com/devicons/devicon/master/icons/tensorflow/tensorflow-original.svg",
  "ResNet50": "https://raw.githubusercontent.com/devicons/devicon/master/icons/tensorflow/tensorflow-original.svg",
  "ngrok": "https://cdn.simpleicons.org/ngrok/white",
  "Render": "https://cdn.simpleicons.org/render/white",
  "Scikit-learn": "https://cdn.simpleicons.org/scikitlearn/white",
  "Gradio": "https://cdn.simpleicons.org/gradio/white"
};
